In [8]:
import dill
dill.load_session('ch10ann.db')

Creating a single Threshold Linear Unit (TLU) which is known as a perceptron

In [9]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

iris = load_iris()

X = iris.data[:, (2,3)] #petal length, petal width
y = (iris.target == 0).astype(np.int)

per_clf = Perceptron()
per_clf.fit(X, y)

y_pred = per_clf.predict([[2, 0.5]])
print('Predicted', y_pred)

Predicted [0]


In [5]:
import tensorflow as tf
from tensorflow import keras

print('Tensorflow version: ',tf.__version__)
print('Keras version: ',keras.__version__)

Tensorflow version:  2.1.0
Keras version:  2.2.4-tf


Image classification using Fashion Mnist, this is different from Mnist as Mnist was digits [0,1,2,3,4,5...9] whereas Fashion Mnist is clothing: Tshirt, trouser, pullover etc]

In [6]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 7s 1us/step


In [16]:
X_train_full.shape
#You have 60000 28 by 28 elements in teh array

(60000, 28, 28)

In [17]:
X_train_full.dtype

dtype('uint8')

In [27]:
#Scaling the pixel intensities, since all are from 0 to 255 -> 0 to 1, also creating a validation set
X_valid, X_train = X_train_full[:5000]/255.0, X_train_full[5000:]/255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]
X_test = X_test/255.0

In [32]:
y_train

array([4, 0, 7, ..., 3, 0, 5], dtype=uint8)

In [23]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", 
               "Ankle boot"]

In [29]:
class_names[y_train[0]]

'Coat'

In [35]:
#Now lets build our MLP
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28,28])) #Convert input to a 1D array
model.add(keras.layers.Dense(300, activation="relu")) #300 Neurons with Relu activation function
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

#All of this can also be parsed as paramters inside Sequential
#model = keras.models.Sequential([
#    keras.layers.Flatten(input_shape=[28,28]),
#    keras.layers.Dense(300, activation="relu"),
#    keras.layers.Dense(100, activation="relu"),
#    keras.layers.Dense(10, activation="softmax")
#])

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.layers

In [41]:
hidden1 = model.layers[1]
hidden1.name

'dense'

In [43]:
model.get_layer('dense') is hidden1

True

In [45]:
weights, biases = hidden1.get_weights()
weights

array([[ 0.00064065, -0.05406202,  0.06755719, ...,  0.04977856,
         0.0735604 ,  0.00520879],
       [ 0.03916007,  0.05973338, -0.02302288, ...,  0.06761892,
         0.06866913,  0.00079568],
       [ 0.06503299, -0.05525991,  0.05248441, ..., -0.01200636,
        -0.01764258, -0.03057273],
       ...,
       [-0.0018555 , -0.02894144, -0.06312636, ..., -0.07225871,
         0.05890697,  0.00673521],
       [ 0.03758623,  0.02471546, -0.02648306, ..., -0.07403474,
        -0.07191742,  0.0514216 ],
       [-0.00858812,  0.02415555,  0.02097904, ..., -0.03425112,
        -0.05430547, -0.02035681]], dtype=float32)

In [46]:
weights.shape

(784, 300)

In [47]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [48]:
biases.shape

(300,)

In [49]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])
#Can also use other ones which is the same and do not have to write the actual word for instance
# sgd = keras.optimizers.SGD(), default learning rate = 0.01
# Using sparse becuase we have 1 to 9 and it has not been one hot encoded
# Can be converted have to use keras.utils.to_categorical()

In [51]:
history = model.fit(X_train, y_train, epochs=30, validation_data=(X_valid, y_valid))
# Can also use validation split = 0.1 which tells keras to use the last 10% of the data (before shuffling) for validation.

Train on 55000 samples, validate on 5000 samples
Epoch 1/30
55000/55000 [==============================] - 4s 71us/sample - loss: 0.2219 - accuracy: 0.9199 - val_loss: 0.3085 - val_accuracy: 0.8912
Epoch 2/30
55000/55000 [==============================] - 4s 69us/sample - loss: 0.2189 - accuracy: 0.9208 - val_loss: 0.2943 - val_accuracy: 0.8944
Epoch 3/30
55000/55000 [==============================] - 4s 69us/sample - loss: 0.2148 - accuracy: 0.9220 - val_loss: 0.2951 - val_accuracy: 0.8918
Epoch 4/30
55000/55000 [==============================] - 4s 71us/sample - loss: 0.2115 - accuracy: 0.9241 - val_loss: 0.2970 - val_accuracy: 0.8898
Epoch 5/30
55000/55000 [==============================] - 4s 69us/sample - loss: 0.2076 - accuracy: 0.9255 - val_loss: 0.3069 - val_accuracy: 0.8918
Epoch 6/30
55000/55000 [==============================] - 4s 69us/sample - loss: 0.2053 - accuracy: 0.9269 - val_loss: 0.2860 - val_accuracy: 0.8980
Epoch 7/30
55000/55000 [==============================] -

In [40]:
import dill
dill.dump_session('ch10ann.db')